import {
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Banknote,
  Bell,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  ClipboardCheck,
  ClipboardList,
  Contact,
  Gift,
  HelpCircle,
  History,
  Home,
  Hourglass,
  Inbox,
  Info,
  KeyRound,
  LayoutDashboard,
  LineChart,
  Lock,
  LogOut,
  Megaphone,
  Menu,
  Phone,
  Plus,
  ReceiptText,
  RefreshCw,
  Search,
  SearchX,
  Send,
  Shield,
  ShieldCheck,
  Smartphone,
  Tag,
  TrendingUp,
  User,
  UserPlus,
  Users,
  Wallet,
  Wifi,
  X,
  type LucideIcon,
} from "lucide-react";

// Maps the Material-Symbols-style names used across the app to lucide icons.
const MAP: Record<string, LucideIcon> = {
  account_balance_wallet: Wallet,
  add: Plus,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  call: Phone,
  campaign: Megaphone,
  check: Check,
  check_circle: CircleCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  contacts: Contact,
  dashboard: LayoutDashboard,
  error: CircleAlert,
  group: Users,
  history: History,
  home: Home,
  hourglass_empty: Hourglass,
  inbox: Inbox,
  info: Info,
  insights: LineChart,
  key: KeyRound,
  lock: Lock,
  logout: LogOut,
  manage_history: History,
  menu: Menu,
  notifications: Bell,
  payments: Banknote,
  pending_actions: ClipboardList,
  person: User,
  person_add: UserPlus,
  phonelink_lock: ShieldCheck,
  receipt_long: ReceiptText,
  redeem: Gift,
  search: Search,
  search_off: SearchX,
  sell: Tag,
  send: Send,
  shield: Shield,
  smartphone: Smartphone,
  sync: RefreshCw,
  task_alt: ClipboardCheck,
  trending_up: TrendingUp,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  wifi: Wifi,
};

export function Icon({
  name,
  className,
}: {
  name: string;
  className?: string;
  /** Accepted for API compatibility; lucide icons are stroke-based. */
  filled?: boolean;
}) {
  const Cmp = MAP[name] ?? HelpCircle;
  // size="1em" lets existing text-[Npx] / text-Nxl font-size classes drive the size,
  // and currentColor (default) makes text-color classes control the stroke color.
  return <Cmp className={className} size="1em" aria-hidden />;
}
